export { Login } from './Login'
export { Register } from './Register'
export { Dashboard } from './Dashboard'
export { ForgotPassword } from './ForgotPassword'
export { ResetPassword } from './ResetPassword'
export { Profile } from './Profile'